INSERT INTO TREN (id, Nombre, Capacitat) VALUES (1, 'Intercity', 200);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (2, 'Regional Express', 150);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (3, 'Viento del Norte', 300);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (4, 'Suburbano', 100);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (5, 'Expreso del Sur', 250);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (6, 'Línea Azul', 180);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (7, 'Expreso Nocturno', 400);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (8, 'Tren de Montaña', 120);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (9, 'Flecha Rápida', 500);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (10, 'Línea Roja', 220);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (11, 'Costa Express', 280);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (12, 'Aurora Boreal', 320);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (13, 'Tren de Alta Velocidad', 600);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (14, 'Vagón de Lujo', 50);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (15, 'Ferroviario Central', 350);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (16, 'Expreso del Este', 230);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (17, 'Tren Urbano', 90);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (18, 'Viento del Este', 310);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (19, 'Rayo de Plata', 450);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (20, 'Línea Dorada', 275);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (21, 'Viaje Estelar', 500);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (22, 'Expreso de Medianoche', 350);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (23, 'Tren del Horizonte', 400);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (24, 'Línea Verde', 150);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (25, 'Tren de los Picos', 120);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (26, 'Expreso Polar', 500);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (27, 'Ruta del Sol', 220);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (28, 'Expreso del Oeste', 180);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (29, 'Tren del Desierto', 130);
INSERT INTO TREN (id, Nombre, Capacitat) VALUES (30, 'Expreso Oceánico', 400);